PICK_SCHEMA = {
    "name": "PickAIResponse",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "result": {"type": "string", "enum": ["BET", "LEAN", "NO_BET"]},
            "market": {
                "type": ["string", "null"],
                "enum": ["ML", "SPREAD", "BTTS", "DC", "DNB", "PROP", "TOTAL", None],
            },
            "emoji": {"type": "string"},
            "selection": {"type": ["string", "null"]},
            "line": {"type": ["number", "null"]},
            "odds_format": {
                "type": ["string", "null"],
                "enum": ["american", "decimal", None],
            },
            "odds": {"type": ["number", "null"]},
            "p_est": {"type": "number", "minimum": 0, "maximum": 1},
            "p_implied": {
                "type": ["number", "null"],
                "minimum": 0,
                "maximum": 1,
            },
            "ev": {"type": ["number", "null"]},
            "confidence": {"type": "integer", "minimum": 0, "maximum": 100},
            "stake_u": {"type": "number", "minimum": 0, "maximum": 2},
            "high_prob_low_payout": {"type": "boolean"},
            "is_value": {"type": "boolean"},
            "reasons": {
                "type": "array",
                "maxItems": 6,
                "items": {"type": "string"},
            },
            "risks": {"type": "array", "items": {"type": "string"}},
            "triggers": {"type": "array", "items": {"type": "string"}},
            "missing_data": {"type": "array", "items": {"type": "string"}},
            "as_of_utc": {"type": "string"},
            "notes": {"type": "string"},
        },
        "required": [
            "result",
            "market",
            "emoji",
            "selection",
            "line",
            "odds_format",
            "odds",
            "p_est",
            "p_implied",
            "ev",
            "confidence",
            "stake_u",
            "high_prob_low_payout",
            "is_value",
            "reasons",
            "risks",
            "triggers",
            "missing_data",
            "as_of_utc",
            "notes",
        ],
    },
}
